repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 #
    hooks:
      - id: check-yaml
        exclude: ^{{ cookiecutter.project_slug }}/
      - id: trailing-whitespace
        exclude: ^{{ cookiecutter.project_slug }}/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        exclude: ^{{ cookiecutter.project_slug }}/
        args: [ --fix ]
      - id: ruff-format
        exclude: ^{{ cookiecutter.project_slug }}/

