[tool.poetry]
name = "cookiecutter-DS"
version = "1.0.0"
description = "A cookiecutter template for creating a DS python package"
authors = ["Riksarkivet"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
cookiecutter = "*"
cruft = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pre-commit = "^3.6.0"
ruff = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
