[project]
name = "{{cookiecutter.package_name}}"
version = "0.0.1.dev0"
description = "short description of project."
readme = "docs/README.md"
requires-python = ">={{cookiecutter.python_interpreter}}"
authors = [ { name = "{{cookiecutter.maintainer}}"  }]
license = { text = "{{cookiecutter.LICENSE}}" }
classifiers = [
    "Intended Audience :: Science/Research",
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Operating System :: Unix",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows"
]

dependencies = ["pandas"]

[project.urls]
homepage = "https://{{cookiecutter.repo_owner}}/{{cookiecutter.repo_name}}"
documentation = "https://readthedocs.org"
repository = "https://github.com"
changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[project.optional-dependencies]
test = ["pytest < 6.0.0", "pytest-cov[all]", "ruff", "black", "mypy", "coverage", "isort", "python-dotenv"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-v --cov={{cookiecutter.package_name}}"
testpaths = ["tests/unit"]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.black]
line-length = 119
target-version = ['py{{ cookiecutter.python_interpreter|replace(".", "") }}']

[tool.ruff]
ignore = ["C901", "E501", "E741", "W605"]
select = ["C", "E", "F", "I", "W"]
line-length = 119

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.isort]
lines-after-imports = 2
known-first-party = ["{{cookiecutter.package_name}}"]
