name: Sanity checks

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python -m pip install pre-commit
      - run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python -m pip install cookiecutter pytest pyyaml
      - run: pytest
